version: '3.8'

services:
  api:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://cache:6379
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - cache

  cache:
    image: redis:7.4.1-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
